"""empty message

Revision ID: 0603346232cf
Revises: 9b60a7883750
Create Date: 2024-07-11 16:04:38.258287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0603346232cf'
down_revision: Union[str, None] = '9b60a7883750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('description', sa.String(), nullable=False))
    op.add_column('client', sa.Column('auto_reply_id', sa.String(), nullable=True))
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('client', 'auto_reply_id')
    op.drop_column('client', 'description')
    # ### end Alembic commands ###
