"""empty message

Revision ID: 690ee9bdbe6f
Revises: 0603346232cf
Create Date: 2024-07-18 12:09:27.252544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690ee9bdbe6f'
down_revision: Union[str, None] = '0603346232cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('working', 'stopped', 'paused', 'finished', name='status'), nullable=False),
    sa.Column('time_start', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('errors', sa.String(), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.add_column('client', sa.Column('username', sa.String(length=128), nullable=False))
    op.add_column('client', sa.Column('photo', sa.String(), nullable=False))
    op.alter_column('client', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'client', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.alter_column('client', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('client', 'photo')
    op.drop_column('client', 'username')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
