"""empty message

Revision ID: 816cd8312114
Revises: 690ee9bdbe6f
Create Date: 2024-07-22 11:38:31.021169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816cd8312114'
down_revision: Union[str, None] = '690ee9bdbe6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('pid', sa.String(), nullable=True))
    op.add_column('task', sa.Column('action_type', sa.Enum('people', 'hashtag', 'parse', name='actiontype'), nullable=False))
    op.add_column('task', sa.Column('progress', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'progress')
    op.drop_column('task', 'action_type')
    op.drop_column('task', 'pid')
    # ### end Alembic commands ###
